<?php

namespace common\models;

use Yii;
use yii\db\BatchQueryResult;

class Post extends BasePost
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    public function serializeToArray()
    {
        $serializedData = [];
        $serializedData['postId'] = $this->id;
        $serializedData['title'] = $this->title;
        $serializedData['createdBy'] = $this->created_by;

        return $serializedData;
    }

}